# Generated by Django 5.1.4 on 2025-03-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
