# Generated by Django 5.1.4 on 2024-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
