# Generated by Django 5.1.3 on 2024-12-10 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_alter_photo_image_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
