# Generated by Django 5.1.4 on 2025-01-11 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_photo_photo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_status',
        ),
        migrations.AddField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('1', 'На удалении'), ('2', 'На модерации'), ('3', 'Одобренно')], default='2', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
