# Generated by Django 5.1.4 on 2025-01-06 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_photo_photo_status'),
        ('viewflow', '0014_alter_process_parent_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_status',
        ),
        migrations.AddField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhotoModerationProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='galery.photo')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
