# Generated by Django 5.1.4 on 2025-01-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_remove_photo_photo_status_photo_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
