# Generated by Django 5.1.4 on 2025-01-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_remove_photo_photo_status_photo_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
