# Generated by Django 5.1.4 on 2024-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_alter_photo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
