# Generated by Django 5.1.4 on 2025-01-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0006_alter_photo_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('1', 'На удалении'), ('2', 'На модерации'), ('3', 'Одобренно'), ('4', 'отклонено')], default='2', max_length=1, verbose_name='Статус'),
        ),
    ]
