# Generated by Django 5.1.4 on 2025-01-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0006_photo_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomoderationprocess',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='photomoderationprocess',
            name='rejected',
        ),
    ]
