# Generated by Django 5.1.4 on 2024-12-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'photo')},
        ),
    ]
