# Generated by Django 5.1.4 on 2025-01-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0007_remove_photomoderationprocess_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
