# Generated by Django 5.1.4 on 2025-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0007_alter_photo_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='old_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/old/', verbose_name='Старая фотография'),
        ),
    ]
