# Generated by Django 5.1.4 on 2025-01-31 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0008_photo_old_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('1', 'На удалении'), ('2', 'На модерации'), ('3', 'Одобрено'), ('4', 'отклонено')], db_index=True, default='2', max_length=1, verbose_name='Статус'),
        ),
    ]
