# Generated by Django 5.1.4 on 2025-02-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'photo')},
        ),
    ]
