# Generated by Django 5.1.4 on 2025-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0011_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
