# Generated by Django 5.1.4 on 2025-03-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0013_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
