# Generated by Django 5.1.7 on 2025-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0015_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
