# Generated by Django 5.1.7 on 2025-03-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0017_remove_comment_can_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='task_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='delete_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи удаления'),
        ),
    ]
