# Generated by Django 5.1.4 on 2025-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0018_remove_photo_task_id_photo_delete_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='old_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/old/%Y/%m/%d/', verbose_name='Старая фотография'),
        ),
    ]
