# Generated by Django 5.1.4 on 2025-03-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0019_alter_photo_old_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('1', 'На удалении'), ('2', 'На модерации'), ('3', 'Одобрено'), ('4', 'Отклонено')], db_index=True, default='2', max_length=1, verbose_name='Статус'),
        ),
    ]
