# Generated by Django 5.1.4 on 2025-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0020_alter_photo_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
    ]
