# Generated by Django 5.1.4 on 2025-04-27 20:25

import galery.models.photo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0021_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=galery.models.photo.models.upload_to, verbose_name='Фотография'),
        ),
    ]
