# Generated by Django 5.1.4 on 2025-04-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0023_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='temp_photos/', verbose_name='Фотография'),
        ),
    ]
