# Generated by Django 5.1.4 on 2025-05-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0025_user_password_reset_token_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(blank=True, choices=[('1', 'На удалении'), ('2', 'На модерации'), ('3', 'Одобрено'), ('4', 'Отклонено')], db_index=True, default='2', max_length=1, verbose_name='Статус'),
        ),
    ]
